<?php
/**
 * LeadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API FFID
 *
 * Documentação de chamadas à API pública FFID.  Você pode encontrar mais sobre o tratamento dos dados no seu [dashboard](https://d.ffid.com.br). Para utilizar esta API é preciso obter uma chave e um segredo (`api_key`, `api_secret`).
 *
 * OpenAPI spec version: 1.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.32
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LeadTest Class Doc Comment
 *
 * @category    Class
 * @description Lead
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LeadTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Lead"
     */
    public function testLead()
    {
    }

    /**
     * Test attribute "e164"
     */
    public function testPropertyE164()
    {
    }

    /**
     * Test attribute "formatted_phone"
     */
    public function testPropertyFormattedPhone()
    {
    }

    /**
     * Test attribute "whatsapp"
     */
    public function testPropertyWhatsapp()
    {
    }

    /**
     * Test attribute "last_seen"
     */
    public function testPropertyLastSeen()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "phone_type"
     */
    public function testPropertyPhoneType()
    {
    }

    /**
     * Test attribute "phone_valid"
     */
    public function testPropertyPhoneValid()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "email_status"
     */
    public function testPropertyEmailStatus()
    {
    }

    /**
     * Test attribute "email_domain"
     */
    public function testPropertyEmailDomain()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "last_search"
     */
    public function testPropertyLastSearch()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }
}
